Services/src/CSClassroom/CSClassroom.WebApp/Controllers/AdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CSC.CSClassroom.Model.Users;
using CSC.CSClassroom.Service.Classrooms;
using CSC.CSClassroom.Service.Identity;
using CSC.CSClassroom.WebApp.Filters;
using CSC.CSClassroom.WebApp.ViewModels.Shared;
using Microsoft.AspNetCore.Mvc;

namespace CSC.CSClassroom.WebApp.Controllers
{
	/// <summary>
	/// The admin controller, which manages administrators of a classroom.
	/// </summary>
	[Route(ClassroomRoutePrefix)]
	public class AdminController : BaseClassroomController
	{
		/// <summary>
		/// The user service.
		/// </summary>
		private IUserService UserService { get; }

		/// <summary>
		/// Constructor.
		/// </summary>
		public AdminController(
			BaseControllerArgs args,
			IClassroomService classroomService,
			IUserService userService)
				: base(args, classroomService)
		{
			UserService = userService;
		}

		/// <summary>
		/// Shows all administrators of the class.
		/// </summary>
		[Route("Admins")]
		[Authorization(RequiredAccess.SuperUser)]
		public async Task<IActionResult> Admins(string className)
		{
			var classroom = await ClassroomService.GetClassroomAsync(className);
			var admins = await ClassroomService.GetClassroomAdminsAsync(className);

			var viewModel = new UserListViewModel
			(
				admins.Select(admin => admin.User).ToList(),
				new List<UserAction>()
				{
						new UserAction
						(
							"Remove",
							user => Url.Action("RemoveAdmin", new {userId = user.Id})
						)
				}
			);

			ViewBag.Classroom = classroom;
			ViewBag.ClassroomRole = ClassroomRole.Admin;

			return View(viewModel);
		}

		/// <summary>
		/// Adds an admin to the class.
		/// </summary>
		[Route("AddAdmin")]
		[Authorization(RequiredAccess.SuperUser)]
		public IActionResult AddAdmin(string className)
		{
			return View(new UserToAdd());
		}

		/// <summary>
		/// Adds an admin to the class.
		/// </summary>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Route("AddAdmin")]
		[Authorization(RequiredAccess.SuperUser)]
		public async Task<IActionResult> AddAdmin(string className, UserToAdd userToAdd)
		{
			var result = await UserService.AddClassroomAdminAsync
			(
				className,
				userToAdd.UserName
			);

			if (result)
			{
				return RedirectToAction("Admins");
			}
			else
			{
				ModelErrors.AddError("UserName", "User not found. (Did the user register?)");
				return View(userToAdd);
			}
		}

		/// <summary>
		/// Removes an admin from the class.
		/// </summary>
		[Route("RemoveAdmin")]
		[Authorization(RequiredAccess.SuperUser)]
		public async Task<IActionResult> RemoveAdmin(string className, int userId)
		{
			var user = await UserService.GetUserAsync(userId);

			return View(user);
		}

		/// <summary>
		/// Removes an admin from the class.
		/// </summary>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Route("RemoveAdmin")]
		[ActionName("RemoveAdmin")]
		[Authorization(RequiredAccess.SuperUser)]
		public async Task<IActionResult> RemoveAdminPost(string className, int userId)
		{
			await UserService.RemoveClassroomAdminAsync(className, userId);

			return RedirectToAction("Admins");
		}
	}
}

Services/src/CSClassroom/CSClassroom.WebApp/Controllers/ClassroomController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CSC.CSClassroom.Model.Classrooms;
using CSC.CSClassroom.Model.Communications;
using CSC.CSClassroom.Model.Users;
using CSC.CSClassroom.Service.Classrooms;
using CSC.CSClassroom.Service.Communications;
using CSC.CSClassroom.Service.Identity;
using CSC.CSClassroom.WebApp.Filters;
using CSC.CSClassroom.WebApp.ViewModels.Shared;
using Microsoft.AspNetCore.Mvc;
using ReflectionIT.Mvc.Paging;

namespace CSC.CSClassroom.WebApp.Controllers
{
	/// <summary>
	/// The classroom controller.
	/// </summary>
	public class ClassroomController : BaseController
	{
		/// <summary>
		/// The classroom service.
		/// </summary>
		private IClassroomService ClassroomService { get; }

		/// <summary>
		/// The user service.
		/// </summary>
		private IUserService UserService { get; }

	    /// <summary>
	    /// The classroom service.
	    /// </summary>
	    private IAnnouncementService AnnouncementService { get; }

        /// <summary>
        /// Constructor.
        /// </summary>
        public ClassroomController(
			BaseControllerArgs args, 
			IClassroomService classroomService,
			IUserService userService,
            IAnnouncementService announcementService) 
				: base(args)
		{
			ClassroomService = classroomService;
			UserService = userService;
		    AnnouncementService = announcementService;

		}

		/// <summary>
		/// Shows all classrooms.
		/// </summary>
		[Route("Classes")]
		[Authorization(RequiredAccess.SuperUser)]
		public async Task<IActionResult> Index()
		{
			var classrooms = await ClassroomService.GetClassroomsAsync();

			return View(classrooms);
		}

		/// <summary>
		/// Creates a new classroom.
		/// </summary>
		[Route("CreateClass")]
		[Authorization(RequiredAccess.SuperUser)]
		public IActionResult Create()
		{
			return View("CreateEdit");
		}

		/// <summary>
		/// Creates a new classroom.
		/// </summary>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Route("CreateClass")]
		[Authorization(RequiredAccess.SuperUser)]
		public async Task<IActionResult> Create(Classroom classroom)
		{
			if (ModelState.IsValid)
			{
				await ClassroomService.CreateClassroomAsync(classroom);

				return RedirectToAction("Index");
			}
			else
			{
				return View("CreateEdit", classroom);
			}
		}

		/// <summary>
		/// Edits a classroom.
		/// </summary>
		[Route("Classes/{className}/Edit")]
		[Authorization(RequiredAccess.SuperUser)]
		public async Task<IActionResult> Edit(string className)
		{
			if (className == null)
			{
				return NotFound();
			}

			var classroom = await ClassroomService.GetClassroomAsync(className);
			if (classroom == null)
			{
				return NotFound();
			}

			return View("CreateEdit", classroom);
		}

		/// <summary>
		/// Edits a classroom.
		/// </summary>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Route("Classes/{className}/Edit")]
		[Authorization(RequiredAccess.SuperUser)]
		public async Task<IActionResult> Edit(string className, Classroom classroom)
		{
			if (ModelState.IsValid)
			{
				await ClassroomService.UpdateClassroomAsync(classroom);

				return RedirectToAction("Index");
			}
			else
			{
				return View("CreateEdit", classroom);
			}
		}

		/// <summary>
		/// Archives a classroom.
		/// </summary>
		[Route("Classes/{className}/Archive")]
		[Authorization(RequiredAccess.SuperUser)]
		public async Task<IActionResult> Archive(string className)
		{
			if (className == null)
			{
				return NotFound();
			}

			var classroom = await ClassroomService.GetClassroomAsync(className);
			if (classroom == null)
			{
				return NotFound();
			}

			return View("Archive", classroom);
		}

		/// <summary>
		/// Archives a classroom.
		/// </summary>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Route("Classes/{className}/Archive")]
		[Authorization(RequiredAccess.SuperUser)]
		public async Task<IActionResult> Archive(
			string className, 
			string archivedClassName)
		{
			var result = await ClassroomService.ArchiveClassroomAsync
			(
				className, 
				archivedClassName
			);

			if (!result)
			{
				return NotFound();
			}

			return RedirectToAction("Index");
		}

		/// <summary>
		/// Deletes a classroom.
		/// </summary>
		[Route("Classes/{className}/Delete")]
		[Authorization(RequiredAccess.SuperUser)]
		public async Task<IActionResult> Delete(string className)
		{
			if (className == null)
			{
				return NotFound();
			}

			var classroom = await ClassroomService.GetClassroomAsync(className);
			if (classroom == null)
			{
				return NotFound();
			}

			return View(classroom);
		}

		/// <summary>
		/// Deletes a classroom.
		/// </summary>
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		[Route("Classes/{className}/Delete")]
		[Authorization(RequiredAccess.SuperUser)]
		public async Task<IActionResult> DeleteConfirmed(string className)
		{
			await ClassroomService.DeleteClassroomAsync(className);

			return RedirectToAction("Index");
		}
	}
}

Services/src/CSClassroom/CSClassroom.WebApp/Controllers/ClassroomHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CSC.CSClassroom.Model.Assignments;
using CSC.CSClassroom.Model.Communications;
using CSC.CSClassroom.Model.Users;
using CSC.CSClassroom.Service.Assignments;
using CSC.CSClassroom.Service.Classrooms;
using CSC.CSClassroom.Service.Communications;
using CSC.CSClassroom.Service.Identity;
using CSC.CSClassroom.WebApp.Extensions;
using CSC.CSClassroom.WebApp.Filters;
using CSC.CSClassroom.WebApp.ViewModels.Assignment;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReflectionIT.Mvc.Paging;

namespace CSC.CSClassroom.WebApp.Controllers
{
	/// <summary>
	/// The announcement controller.
	/// </summary>
	[Route(ClassroomRoutePrefix)]
	public class ClassroomHomeController : BaseClassroomController
	{
		/// <summary>
		/// The classroom service.
		/// </summary>
		private IAnnouncementService AnnouncementService { get; }

		/// <summary>
		/// Constructor.
		/// </summary>
		public ClassroomHomeController(
			BaseControllerArgs args,
			IClassroomService classroomService,
			IAnnouncementService announcementService)
				: base(args, classroomService)
		{
			AnnouncementService = announcementService;
		}

		/// <summary>
		/// Shows the home page for the class.
		/// </summary>
		[Route("")]
		[ClassroomAuthorization(ClassroomRole.General)]
		public async Task<IActionResult> Index(int page = 1)
		{
			var announcementsQuery = await AnnouncementService.GetAnnouncementsAsync
			(
				ClassroomName, 
				User.Id,
				ClassroomRole >= ClassroomRole.Admin
			);

			var announcements = await PagingList.CreateAsync
			(
				announcementsQuery,
				pageSize: 5,
				pageIndex: page
			);

			return View(announcements);
		}

		/// <summary>
		/// Creates a new assignment.
		/// </summary>
		[Route("PostAnnouncement")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public IActionResult PostAnnouncement()
		{
			ViewBag.OperationType = "Post";
			return View("PostEditAnnouncement");
		}

		/// <summary>
		/// Creates a new assignment.
		/// </summary>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Route("PostAnnouncement")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public async Task<IActionResult> PostAnnouncement(Announcement announcement)
		{
			ModelState[nameof(Announcement.DatePosted)].ValidationState 
                = ModelValidationState.Valid;

			if (ModelState.IsValid
			    && await AnnouncementService.PostAnnouncementAsync
					(
						ClassroomName, 
						User.Id, 
						announcement,
						FormatDateTime,
						ModelErrors
					))
			{
				return RedirectToAction("Index");
			}
			else
			{
				ViewBag.OperationType = "Post";
				return View("PostEditAnnouncement", announcement);
			}
		}

		/// <summary>
		/// Edits an announcement.
		/// </summary>
		[Route("EditAnnouncement")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public async Task<IActionResult> EditAnnouncement(int announcementId)
		{
			var announcement = await AnnouncementService.GetAnnouncementAsync
			(
				ClassroomName,
				announcementId
			);

			if (announcement == null)
			{
				return NotFound();
			}

			ViewBag.OperationType = "Edit";
			return View("PostEditAnnouncement", announcement);
		}

		/// <summary>
		/// Edits an announcement.
		/// </summary>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Route("EditAnnouncement")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public async Task<IActionResult> EditAnnouncement(Announcement announcement)
		{
			ModelState[nameof(Announcement.DatePosted)].ValidationState
				= ModelValidationState.Valid;

			if (ModelState.IsValid
			    && await AnnouncementService.EditAnnouncementAsync
			    (
				    ClassroomName,
				    announcement,
					FormatDateTime,
				    ModelErrors
			    ))
			{
				return RedirectToAction("Index");
			}
			else
			{
				ViewBag.OperationType = "Edit";
				return View("PostEditAnnouncement", announcement);
			}
		}


		/// <summary>
		/// Deletes an announcement.
		/// </summary>
		[Route("Announcements/{announcementId}/Delete")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public async Task<IActionResult> DeleteAnnouncement(int announcementId)
		{
			var announcement = await AnnouncementService.GetAnnouncementAsync
			(
				ClassroomName, 
				announcementId
			);

			if (announcement == null)
			{
				return NotFound();
			}

			return View(announcement);
		}

		/// <summary>
		/// Deletes an announcement.
		/// </summary>
		[HttpPost, ActionName("DeleteAnnouncement")]
		[ValidateAntiForgeryToken]
		[Route("Announcements/{announcementId}/Delete")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public async Task<IActionResult> DeleteAnnouncementConfirmed(int announcementId)
		{
			await AnnouncementService.DeleteAnnouncementAsync(ClassroomName, announcementId);

			return RedirectToAction("Index");
		}

		/// <summary>
		/// Formats the given datetime object.
		/// </summary>
		private string FormatDateTime(DateTime dateTime)
		{
			return dateTime.FormatLongDateTime(TimeZoneProvider);
		}
	}
}

Services/src/CSClassroom/CSClassroom.WebApp/Views/Classroom/Archive.cshtml
@model Classroom

@{
    ViewData["Title"] = "Archive";
}

<h2>Archive Class</h2>
<span>Archiving a class renames the current class to a new name. It then creates a new version of the class with the current name. The new version of the class contains all assignments and projects of the current class, but no sections/students/submissions.</span>
<form asp-action="Archive">
    <div class="form-horizontal">
        <div class="form-group">
            <label class="col-md-2 control-label">Archived Class Name</label>
            <div class="col-md-10">
                <p class="form-control-static">Enter the name of the archived version of this class.</p>
                <input name="archivedClassName" class="form-control" type="text" value="@(Model.Name + "-Archived")" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Archive" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Services/src/CSClassroom/CSClassroom.WebApp/Views/Classroom/CreateEdit.cshtml
@model Classroom

@{
    var actionName = $"{ViewContext.RouteData.Values["action"]}";
    ViewData["Title"] = actionName;
}

<h2>@actionName Class</h2>

<form asp-action="@actionName">
    <div class="form-horizontal">
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @if (Model != null && Model.Id > 0)
        {
            <input type="hidden" asp-for="Id" />
        }
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <p asp-description-for="Name" class="form-control-static"></p>
                <input asp-for="Name" class="form-control" /> 
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DisplayName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <p asp-description-for="DisplayName" class="form-control-static"></p>
                <input asp-for="DisplayName" class="form-control" />
                <span asp-validation-for="DisplayName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IsActive" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <p asp-description-for="IsActive" class="form-control-static"></p>
                <input asp-for="IsActive" class="checkbox" type="checkbox" value="true" />
                <input type="hidden" name="IsActive" value="false" />
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="GitHubOrganization" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <p asp-description-for="GitHubOrganization" class="form-control-static"></p>
                <input asp-for="GitHubOrganization" class="form-control" />
                <span asp-validation-for="GitHubOrganization" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DefaultTimeDue" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <p asp-description-for="DefaultTimeDue" class="form-control-static"></p>
                <input asp-for="DefaultTimeDue" class="form-control" />
                <span asp-validation-for="DefaultTimeDue" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DailyLatenessDeduction" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <p asp-description-for="DailyLatenessDeduction" class="form-control-static"></p>
                <input asp-for="DailyLatenessDeduction" class="form-control" />
                <span asp-validation-for="DailyLatenessDeduction" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="MaxLatenessDeduction" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <p asp-description-for="MaxLatenessDeduction" class="form-control-static"></p>
                <input asp-for="MaxLatenessDeduction" class="form-control" />
                <span asp-validation-for="MaxLatenessDeduction" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ClassroomGradebooks" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <p asp-description-for="ClassroomGradebooks" class="form-control-static"></p>
                <table id="classroomGradebooks" class="equal-width"></table>
                <span asp-validation-for="ClassroomGradebooks" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@actionName" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

@await Component.InvokeAsync(
    "DynamicTable",
    new
    {
        tableElementId = "classroomGradebooks",
        modelExplorer = ViewData.ModelExplorer.GetExplorerForProperty(nameof(Classroom.ClassroomGradebooks)),
        properties = new[]
        {
            nameof(ClassroomGradebook.Name)
        },
        orderByProp = nameof(ClassroomGradebook.Order),
        startMinRows = 0,
        textAreas = false
    })

Services/src/CSClassroom/CSClassroom.WebApp/Views/Classroom/Delete.cshtml
@model Classroom

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Classroom</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

Services/src/CSClassroom/CSClassroom.WebApp/Views/Classroom/Index.cshtml
@model IEnumerable<Classroom>

@{
    ViewData["Title"] = "Classes";
}

<h2>Classes</h2>

<p>
    <a asp-action="Create">Create Class</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DisplayName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DisplayName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                <a asp-action="Index" asp-controller="ClassroomHome" asp-route-className="@item.Name">Home</a> |
                <a asp-action="Admins" asp-controller="Admin" asp-route-className="@item.Name">Admins</a> |
                <a asp-action="Edit" asp-route-className="@item.Name">Edit</a> |
                <a asp-action="Archive" asp-route-className="@item.Name">Archive</a> |
                <a asp-action="Delete" asp-route-className="@item.Name">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>