Services/src/CSClassroom/CSClassroom.WebApp/ViewModels/Project/CheckForCommitsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSC.CSClassroom.WebApp.ViewModels.Project
{
	using Project = Model.Projects.Project;

	/// <summary>
	/// View model for "Check for commits" confirmation page.
	/// </summary>
    public class CheckForCommitsViewModel
	{
		/// <summary>
		/// The project.
		/// </summary>
		public Project Project { get; }

		/// <summary>
		/// The user.
		/// </summary>
		public int UserId { get; } 

		/// <summary>
		/// Constructor.
		/// </summary>
		public CheckForCommitsViewModel(Project project, int userId)
		{
			Project = project;
			UserId = userId;
		}
	}
}

Services/src/CSClassroom/CSClassroom.WebApp/ViewModels/Project/CreateStudentReposViewModel.cs
using System.Collections.Generic;
using System.Linq;
using CSC.CSClassroom.Model.Projects;
using CSC.CSClassroom.Model.Projects.ServiceResults;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CSC.CSClassroom.WebApp.ViewModels.Project
{
	/// <summary>
	/// The view model for the CreateStudentRepositories page.
	/// </summary>
	public class CreateStudentReposViewModel
	{
		/// <summary>
		/// The project.
		/// </summary>
		public Model.Projects.Project Project { get; }

		/// <summary>
		/// The files in the project.
		/// </summary>
		public IList<ProjectRepositoryFile> Files { get; }

		/// <summary>
		/// The section options for creating repositories.
		/// </summary>
		public IList<SelectListItem> Sections { get; }

		/// <summary>
		/// Constructor.
		/// </summary>
		public CreateStudentReposViewModel(Model.Projects.Project project, IList<ProjectRepositoryFile> files)
		{
			Project = project;
			Files = files;
			Sections = project.Classroom.Sections
				.Select(s => new SelectListItem() { Text = s.DisplayName, Value = s.Name })
				.ToList();
		}
	}
}

Services/src/CSClassroom/CSClassroom.WebApp/ViewModels/Project/ProjectStatusResultsViewModel.cs
using System.Collections.Generic;
using System.Linq;
using CSC.CSClassroom.Model.Projects;
using CSC.CSClassroom.Model.Projects.ServiceResults;
using CSC.CSClassroom.WebApp.Providers;

namespace CSC.CSClassroom.WebApp.ViewModels.Project
{
	/// <summary>
	/// The view model for the status of all projects with one or more builds.
	/// </summary>
	public class ProjectStatusResultsViewModel
	{
		/// <summary>
		/// The user's last name.
		/// </summary>
		public string LastName { get; }

		/// <summary>
		/// The user's first name.
		/// </summary>
		public string FirstName { get; }

		/// <summary>
		/// The user's id.
		/// </summary>
		public int UserId { get; }

		/// <summary>
		/// Each project's status.
		/// </summary>
		public IList<ProjectStatusViewModel> ProjectStatus { get; }

		/// <summary>
		/// Constructor.
		/// </summary>
		public ProjectStatusResultsViewModel(
			ProjectStatusResults projectStatusResults,
			ITimeZoneProvider timeZoneProvider)
		{
			LastName = projectStatusResults.LastName;
			FirstName = projectStatusResults.FirstName;
			UserId = projectStatusResults.UserId;
			ProjectStatus = projectStatusResults.ProjectStatus
				.Select
				(
					projectStatus => new ProjectStatusViewModel
					(
						projectStatus, 
						timeZoneProvider
					)
				).ToList();
		}
	}
}

Services/src/CSClassroom/CSClassroom.WebApp/Controllers/BuildController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CSC.Common.Infrastructure.Extensions;
using CSC.Common.Infrastructure.Serialization;
using CSC.CSClassroom.Model.Projects;
using CSC.CSClassroom.Model.Projects.ServiceResults;
using CSC.CSClassroom.Model.Users;
using CSC.CSClassroom.Service.Classrooms;
using CSC.CSClassroom.Service.Projects;
using CSC.CSClassroom.WebApp.Extensions;
using CSC.CSClassroom.WebApp.Filters;
using CSC.CSClassroom.WebApp.ViewHelpers.NestedTables;
using CSC.CSClassroom.WebApp.ViewModels.Build;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;

namespace CSC.CSClassroom.WebApp.Controllers
{
	/// <summary>
	/// The section controller.
	/// </summary>
	[Route(ProjectRoutePrefix)]
	public class BuildController : BaseProjectController
	{
		/// <summary>
		/// The section service.
		/// </summary>
		private ISectionService SectionService { get; }

		/// <summary>
		/// The build service.
		/// </summary>
		private IBuildService BuildService { get; }

		/// <summary>
		/// The checkpoint service.
		/// </summary>
		private ICheckpointService CheckpointService { get; }

		/// <summary>
		/// The submission service.
		/// </summary>
		private ISubmissionService SubmissionService { get; }

		/// <summary>
		/// The time zone provider.
		/// </summary>
		private readonly IJsonSerializer _jsonSerializer;

		/// <summary>
		/// Constructor.
		/// </summary>
		public BuildController(
			BaseControllerArgs args,
			IClassroomService classroomService,
			ISectionService sectionService,
			IProjectService projectService,
			IBuildService buildService,
			ICheckpointService checkpointService,
			ISubmissionService submissionService,
			IJsonSerializer jsonSerializer)
				: base(args, classroomService, projectService)
		{
			SectionService = sectionService;
			BuildService = buildService;
			CheckpointService = checkpointService;
			SubmissionService = submissionService;
			_jsonSerializer = jsonSerializer;
		}

		/// <summary>
		/// Returns the user's latest build.
		/// </summary>
		[Route("Builds")]
		[ClassroomAuthorization(ClassroomRole.General)]
		public IActionResult Index()
		{
			return RedirectToAction("LatestBuildResult");
		}

		/// <summary>
		/// Returns the results of a build with the given ID.
		/// </summary>
		[Route("Builds/latestBuild")]
		[ClassroomAuthorization(ClassroomRole.General)]
		public async Task<IActionResult> LatestBuildResult(int? userId)
		{
			if (!Project.ExplicitSubmissionRequired)
			{
				return NotFound();
			}

			if (userId == null)
			{
				userId = User.Id;
			}

			if (userId != User.Id && ClassroomRole < ClassroomRole.Admin)
			{
				return Forbid();
			}

			var latestBuildResult = await BuildService.GetLatestBuildResultAsync
			(
				ClassroomName,
				ProjectName, 
				userId.Value
			);

			if (latestBuildResult == null)
			{
				return NotFound();
			}

			var unreadFeedback = await SubmissionService.GetUnreadFeedbackAsync
			(
				ClassroomName,
				userId.Value
			);

			if (latestBuildResult.BuildResult != null)
			{
				var buildViewModel = GetBuildViewModelAsync
				(
					latestBuildResult.BuildResult, 
					unreadFeedback
				);

				return View("BuildResult", buildViewModel);
			}
			else
			{
				var buildInProgressViewModel = new BuildInProgressViewModel
				(
					latestBuildResult.Commit, 
					latestBuildResult.EstimatedBuildDuration.Value
				);

				return View("BuildInProgress", buildInProgressViewModel);
			}
		}

		/// <summary>
		/// Returns the results of a build with the given ID.
		/// </summary>
		[Route("Builds/{buildId:int}")]
		[ClassroomAuthorization(ClassroomRole.General)]
		public async Task<IActionResult> BuildResult(int buildId)
		{
			if (!Project.ExplicitSubmissionRequired)
			{
				return NotFound();
			}

			var buildResult = await BuildService.GetBuildResultAsync
			(
				ClassroomName, 
				ProjectName, 
				buildId
			);

			if (buildResult == null)
			{
				return NotFound();
			}

			if (buildResult.Build.Commit.UserId != User.Id 
				&& ClassroomRole < ClassroomRole.Admin)
			{
				return Forbid();
			}

			var unreadFeedback = await SubmissionService.GetUnreadFeedbackAsync
			(
				ClassroomName,
				buildResult.Build.Commit.UserId
			);

			var viewModel = GetBuildViewModelAsync(buildResult, unreadFeedback);

			return View(viewModel);
		}

		/// <summary>
		/// Returns the results of all builds in the given section.
		/// </summary>
		[Route("Builds/{sectionName}")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public async Task<IActionResult> SectionBuildResults(string sectionName)
		{
			if (!Project.ExplicitSubmissionRequired)
			{
				return NotFound();
			}

			var section = Classroom.Sections.SingleOrDefault(s => s.Name == sectionName);
			if (section == null)
			{
				return NotFound();
			}

			var builds = await BuildService.GetSectionBuildsAsync
			(
				ClassroomName, 
				ProjectName, 
				sectionName
			);

			var testCounts = GetTestCounts(builds);
			var tableInfo = GetSectionBuildsTableInfo(testCounts, builds);
			var tableData = GetSectionBuildsTableData(builds, testCounts.Keys);

			var viewModel = new SectionBuildResultsViewModel
			(
				section.DisplayName, 
				tableInfo, 
				tableData
			);

			return View(viewModel);
		}

		/// <summary>
		/// Returns the progress of the latest build.
		/// </summary>
		[Route("BuildProgress")]
		[ClassroomAuthorization(ClassroomRole.General)]
		public async Task<IActionResult> MonitorProgress(int userId)
		{
			if (!Project.ExplicitSubmissionRequired)
			{
				return NotFound();
			}

			if (userId != User.Id && ClassroomRole < ClassroomRole.Admin)
			{
				return Forbid();
			}

			var buildProgress = await BuildService.MonitorProgressAsync
			(
				ClassroomName,
				ProjectName,
				userId
			);

			if (buildProgress == null)
			{
				return NotFound();
			}

			return Json(buildProgress);
		}

		/// <summary>
		/// Returns a user's build history.
		/// </summary>
		[Route("BuildHistory")]
		[ClassroomAuthorization(ClassroomRole.General)]
		public async Task<IActionResult> History(int? userId)
		{
			if (!Project.ExplicitSubmissionRequired)
			{
				return NotFound();
			}

			if (userId == null)
			{
				userId = User.Id;
			}

			if (userId != User.Id && ClassroomRole < ClassroomRole.Admin)
			{
				return Forbid();
			}

			var builds = await BuildService.GetUserBuildsAsync
			(
				ClassroomName, 
				ProjectName, 
				userId.Value
			);

			if (builds.Count == 0)
			{
				return NotFound();
			}

			var viewModel = new HistoryViewModel(builds.First().Commit.User, builds);

			return View(viewModel);
		}

		/// <summary>
		/// Shows a single test result.
		/// </summary>
		[Route("Builds/{buildId:int}/TestResult/{testResultId:int}")]
		[ClassroomAuthorization(ClassroomRole.General)]
		public async Task<IActionResult> TestResult(int buildId, int testResultId)
		{
			if (!Project.ExplicitSubmissionRequired)
			{
				return NotFound();
			}

			var testResult = await BuildService.GetTestResultAsync
			(
				ClassroomName,
				ProjectName,
				testResultId
			);

			if (testResult == null || testResult.BuildId != buildId)
			{
				return NotFound();
			}

			if (testResult.Build.Commit.UserId != User.Id && ClassroomRole < ClassroomRole.Admin)
			{
				return Forbid();
			}

			var viewModel = new TestResultViewModel(testResult);

			return View(viewModel);
		}

		/// <summary>
		/// Returns the view model for the given build.
		/// </summary>
		private BuildViewModel GetBuildViewModelAsync(
			BuildResult buildResult,
			IList<UnreadFeedbackResult> unreadFeedback)
		{
			return new BuildViewModel
			(
				buildResult,
				unreadFeedback,
				b => b.Commit.GetCommitUrl(Url),
				testResult => Url.Action
				(
					"TestResult",
					new
					{
						buildId = testResult.BuildId,
						testResultId = testResult.Id
					}
				),
				(projectName, checkpointName, submissionId) => Url.Action
				(
					"ViewFeedback",
					"Submission",
					new
					{
						projectName,
						checkpointName,
						submissionId
					}
				),
				TimeZoneProvider
			);
		}

		/// <summary>
		/// Returns a list of test counts, by class name.
		/// </summary>
		private IDictionary<TestClass, int> GetTestCounts(IEnumerable<Build> builds)
		{
			var testCounts = new Dictionary<TestClass, int>();
			var buildLastSeen = new Dictionary<string, DateTime>();

			// We go through all builds, since some builds might have had tests
			// fail before running some test classes.
			foreach (var build in builds)
			{
				if (build.TestResults != null)
				{
					foreach (var testClass in build.Commit.Project.TestClasses)
					{
						if (!buildLastSeen.ContainsKey(testClass.ClassName) 
							|| build.Commit.PushDate > buildLastSeen[testClass.ClassName])
						{
							if (buildLastSeen.ContainsKey(testClass.ClassName))
							{
								testCounts.Remove(testClass);
							}

							testCounts[testClass] = build.TestResults
								.Count(tr => tr.ClassName == testClass.ClassName);

							buildLastSeen[testClass.ClassName] = build.Commit.PushDate;
						}
					}
				}
			}

			return testCounts;
		}

		/// <summary>
		/// Returns table metadata containing column info.
		/// </summary>
		private static TableInfo GetSectionBuildsTableInfo(
			IDictionary<TestClass, int> testCounts,
			IList<Build> builds)
		{
			var buildIdentifierColumns = new List<TableColumnInfo>()
			{
				new TableColumnInfo("LastName", "Last Name"),
				new TableColumnInfo("FirstName", "First Name"),
				new TableColumnInfo("BuildSucceeded", "Built?"),
				new TableColumnInfo("BuildTime", "Build time")
			};

			var allTestsColumn = new TableColumnInfo("AllTests", $"All tests ({testCounts.Values.Sum()})");

			var testResultColumns = testCounts
				.Keys
				.OrderBy(testClass => testClass.Order)
				.Select
				(
					testClass => new TableColumnInfo
					(
						testClass.ClassName.ToAlphaNumeric(),

Services/src/CSClassroom/CSClassroom.WebApp/Controllers/CheckpointController.cs
using System.Threading.Tasks;
using CSC.CSClassroom.Model.Projects;
using CSC.CSClassroom.Model.Users;
using CSC.CSClassroom.Service.Classrooms;
using CSC.CSClassroom.Service.Projects;
using CSC.CSClassroom.WebApp.Filters;
using Microsoft.AspNetCore.Mvc;

namespace CSC.CSClassroom.WebApp.Controllers
{
	/// <summary>
	/// The checkpoint controller.
	/// </summary>
	[Route(ProjectRoutePrefix)]
	public class CheckpointController : BaseProjectController
	{
		/// <summary>
		/// The section service.
		/// </summary>
		private ISectionService SectionService { get; }

		/// <summary>
		/// The checkpoint service.
		/// </summary>
		private ICheckpointService CheckpointService { get; }

		/// <summary>
		/// Constructor.
		/// </summary>
		public CheckpointController(
			BaseControllerArgs args,
			IClassroomService classroomService,
			ISectionService sectionService,
			IProjectService projectService,
			ICheckpointService checkpointService)
				: base(args, classroomService, projectService)
		{
			SectionService = sectionService;
			CheckpointService = checkpointService;
		}

		/// <summary>
		/// Shows all sections.
		/// </summary>
		[Route("Checkpoints")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public async Task<IActionResult> Index()
		{
			var checkpoints = await CheckpointService.GetCheckpointsAsync
			(
				ClassroomName, 
				ProjectName
			);

			return View(checkpoints);
		}

		/// <summary>
		/// Creates a new checkpoint.
		/// </summary>
		[Route("CreateCheckpoint")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public IActionResult Create()
		{
			return View("CreateEdit");
		}

		/// <summary>
		/// Creates a new checkpoint.
		/// </summary>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Route("CreateCheckpoint")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public async Task<IActionResult> Create(Checkpoint checkpoint)
		{
			if (ModelState.IsValid)
			{
				var succeeded = await CheckpointService.CreateCheckpointAsync
				(
					ClassroomName,
					ProjectName,
					checkpoint,
					ModelErrors
				);

				if (succeeded)
				{
					return RedirectToAction("Index");
				}
			}

			return View("CreateEdit", checkpoint);
		}

		/// <summary>
		/// Edits a checkpoint.
		/// </summary>
		[Route("Checkpoints/{checkpointName}/Edit")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public async Task<IActionResult> Edit(string checkpointName)
		{
			if (checkpointName == null)
			{
				return NotFound();
			}

			var checkpoint = await CheckpointService.GetCheckpointAsync
			(
				ClassroomName, 
				ProjectName, 
				checkpointName
			);

			if (checkpoint == null)
			{
				return NotFound();
			}

			return View("CreateEdit", checkpoint);
		}

		/// <summary>
		/// Edits a checkpoint.
		/// </summary>
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Route("Checkpoints/{checkpointName}/Edit")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public async Task<IActionResult> Edit(Checkpoint checkpoint)
		{
			if (ModelState.IsValid)
			{
				var succeeded = await CheckpointService.UpdateCheckpointAsync
				(
					ClassroomName,
					ProjectName,
					checkpoint,
					ModelErrors
				);

				if (succeeded)
				{
					return RedirectToAction("Index");
				}
			}

			return View("CreateEdit", checkpoint);
		}

		/// <summary>
		/// Deletes a checkpoint.
		/// </summary>
		[Route("Checkpoints/{checkpointName}/Delete")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public async Task<IActionResult> Delete(string checkpointName)
		{
			if (checkpointName == null)
			{
				return NotFound();
			}

			var checkpoint = await CheckpointService.GetCheckpointAsync
			(
				ClassroomName,
				ProjectName,
				checkpointName
			);

			if (checkpoint == null)
			{
				return NotFound();
			}

			return View(checkpoint);
		}

		/// <summary>
		/// Deletes a checkpoint.
		/// </summary>
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		[Route("Checkpoints/{checkpointName}/Delete")]
		[ClassroomAuthorization(ClassroomRole.Admin)]
		public async Task<IActionResult> DeleteConfirmed(string checkpointName)
		{
			await CheckpointService.DeleteCheckpointAsync
			(
				ClassroomName, 
				ProjectName, 
				checkpointName
			);

			return RedirectToAction("Index");
		}
	}
}

Services/src/CSClassroom/CSClassroom.WebApp/Views/Project/Admin.cshtml
@using CSC.Common.Infrastructure.Utilities
@model IEnumerable<Project>

@{
    ViewData["Title"] = "Projects";
}

<h2>Class Projects</h2>

<p>
    <a asp-action="Create">Create Project</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExplicitSubmissionRequired)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.OrderBy(p => p.Name, new NaturalComparer()))
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExplicitSubmissionRequired, "YesNo")
            </td>
            <td>
                <a asp-action="CreateStudentRepositories" asp-route-projectName="@item.Name">Create Repositories</a> |
                <a asp-action="SectionReport" asp-route-projectName="@item.Name">Build Status</a> |
                <a asp-action="Index" asp-controller="Checkpoint" asp-route-projectName="@item.Name">Checkpoints and Grading</a> |
                <a asp-action="CheckForCommitsAllStudents" asp-route-projectName="@item.Name">Missed Commits</a> |
                <a asp-action="Edit" asp-route-projectName="@item.Name">Edit</a> |
                <a asp-action="Delete" asp-route-projectName="@item.Name">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Services/src/CSClassroom/CSClassroom.WebApp/Views/Project/CheckForCommits.cshtml
@model CheckForCommitsViewModel

@{
    ViewData["Title"] = "Check for commits";
}

<h2>Check for commits</h2>
<h4 style="color: blue; font-weight: bold">Project: @Model.Project.Name</h4>

<div style="max-width: 700px">
    <p>Normally, you will see progress for your build shortly after you commit. 
        However, occasionally GitHub has problems that cause builds to be delayed. 
        If you have commited more than <b>one full minute</b> ago, and are not seeing 
        build progress for your commit, you can click the button below to check GitHub
        for your commit (and start your build).</p>
    <p style="color: red; font-weight: bold">Do NOT click the button below if you
        have not yet waited a full minute since your commit. All attempts are logged.</p>
    <div>
        <form asp-action="CheckForCommitsConfirmed" method="post">
            <input type="hidden" name="userId" value="@Model.UserId" />
            <div class="form-actions no-color">
                <input type="submit" value="Check for commits" class="btn btn-default" />
                <p></p>
                <a asp-action="LatestBuildResult" asp-controller="Build" asp-route-userId="@Model.UserId">Back to latest build</a>
            </div>
        </form>
    </div>
</div>

Services/src/CSClassroom/CSClassroom.WebApp/Views/Project/CheckForCommitsAllStudents.cshtml
@model Project

@{
    ViewData["Title"] = "Check for commits";
}

<h2>Check for commits</h2>
<h4 style="color: blue; font-weight: bold">Project: @Model.Name</h4>

<div style="max-width: 700px">
    <p>
        This operation will look at all commits for the given project by all 
        students, and queue up builds for any previously unknown commits. This 
        is an expensive operation that should rarely be executed.
    </p>
    <div>
        <form asp-action="CheckForCommitsAllStudentsConfirmed" method="post">
            <div class="form-actions no-color">
                <input type="submit" value="Check for commits" class="btn btn-default" />
                <p></p>
                <a asp-action="Admin">Back to project list</a>
            </div>
        </form>
    </div>
</div>

Services/src/CSClassroom/CSClassroom.WebApp/Views/Project/CreateStudentRepositoryResults.cshtml
@using CSC.CSClassroom.Model.Projects.ServiceResults
@model IList<CSC.CSClassroom.Model.Projects.ServiceResults.CreateStudentRepoResult>

@{
    ViewData["Title"] = "Student repository results";
}

<h2>Student repository results</h2>

<table id="results" class="table">
    <tr>
        <th>Student name</th>
        <th>Repository result</th>
    </tr>
    @foreach (var result in Model)
    {
        <tr>
            <td>
                @($"{result.Student.LastName}, {result.Student.FirstName}")
            </td>
            <td>
                @{ string color; }
                @switch (result.CreateAndPushResult)
                {
                    case CreateAndPushResult.Exists:
                        color = "blue";
                        break;
                    
                    case CreateAndPushResult.Created:
                    case CreateAndPushResult.Overwritten:
                        color = "green";
                        break;

                    case CreateAndPushResult.Failed:
                    default:
                        color = "red";
                        break;
                }
                
                <p style="color: @color">@result.CreateAndPushResult.ToString()</p>
            </td>
        </tr>
    }

</table>
   

Services/src/CSClassroom/CSClassroom.WebApp/Views/Project/Delete.cshtml
@model Project

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

Services/src/CSClassroom/CSClassroom.WebApp/Views/Project/Index.cshtml
@using CSC.CSClassroom.WebApp.Extensions
@using CSC.CSClassroom.WebApp.Providers
@using CSC.CSClassroom.Model.Users
@model ProjectStatusResultsViewModel
@{
    ViewData["Title"] = "Project Status";
}

<style>
.table-curved {
    border-collapse: separate;
}
.table-curved {
    border: solid black 1px;
    border-radius: 6px;
}
.table-curved th { border-bottom: 1px solid black }
.table-curved td { border-left: 1px solid black; border-bottom: 1px solid black }

</style>
<script>
    function copyToClipboard(link) {
        var $temp = $("<input>");
        $("body").append($temp);
        $temp.val(link).select();
        document.execCommand("copy");
        $temp.remove();
    }
</script>
<h2>Projects</h2>
<h4 style="color: blue">Student: @Model.FirstName @Model.LastName</h4>
@if (ClassroomRole >= ClassroomRole.Admin)
{
    @Html.ActionLink("Manage Projects", "Admin")
    <br />
}
<br />
<div class="panel-group">
    @foreach (var projectStatus in Model.ProjectStatus)
    {
        <div class="panel panel-primary" style="width: 410px">
            <div class="panel-heading" style="font-size: 18px">
                <a data-toggle="collapse" href="#collapse@(projectStatus.ProjectName)" style="color: white">@projectStatus.ProjectName</a>
            </div>
            <div id="collapse@(projectStatus.ProjectName)" class="@(projectStatus == Model.ProjectStatus.First() ? "panel-collapse collapse in" : "panel-collapse collapse")">
                <div class="panel-body">
                    @if (projectStatus.TestTrend.AllBuildTestCounts.Any())
                    {
                        @Html.Partial("~/Views/Build/_TestTrend.cshtml", projectStatus.TestTrend)
                        <br />
                    }
                    <table class="table table-curved">
                        <tr>
                            <th style="text-align: left; border-top: none">
                                Import
                            </th>
                            <td>
                                @{var projectLink = $"https://github.com/{Classroom.GitHubOrganization}/{projectStatus.RepoName}"; }
                                <button onclick="copyToClipboard('@projectLink')">Copy Project Link</button>
                            </td>
                        </tr>
                        <tr>
                            <th style="text-align: left; border-top: none">
                                Last Commit Date
                            </th>
                            <td>
                                @projectStatus.LastCommitDate
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Last Build Succeeded
                            </th>
                            <td style="color: @(projectStatus.LastBuildSucceeded ? "green" : "red"); font-weight: bold; border-left: 1px solid black">
                                @(projectStatus.LastBuildSucceeded ? "Yes" : "No")
                            </td>
                        </tr>
                        @{
                            var lastBuild = projectStatus.TestTrend.AllBuildTestCounts.LastOrDefault();
                        }
                        @if (projectStatus.LastBuildSucceeded && lastBuild != null)
                        {
                            <tr>
                                <th>
                                    Test Results
                                </th>
                                <td>
                                    @(lastBuild.PassedCount) / @(lastBuild.PassedCount + lastBuild.FailedCount)
                                </td>
                            </tr>
                        }
                        <tr>
                            <th style="border-bottom: 0px">
                                Build Result
                            </th>
                            <td style="border-bottom: 0px">
                                @Html.ActionLink("Latest Build", "LatestBuildResult", "Build", new {projectName = projectStatus.ProjectName, userId = Model.UserId})
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    }
</div>